const cardiologyApi = [
    {
        id:1,
        images:"image/dr.png",
        name:"Dr. Mahi Rawat",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
    {
        id:2,
        images:"image/dr1.png",
        name:"Dr. Rohan Sharma",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
    {
        id:3,
        images:"image/dr2.png",
        name:"Dr. Sakshi Sena",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
    {
        id:4,
        images:"image/dr3.png",
        name:"Dr. Mahi Rawat",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
    {
        id:5,
        images:"image/dr.png",
        name:"Dr. Mahi Rawat",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
    {
        id:6,
        images:"image/dr1.png",
        name:"Dr. Rohan Sharma",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
    {
        id:7,
        images:"image/dr2.png",
        name:"Dr. Sakshi Sena",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
    {
        id:8,
        images:"image/dr3.png",
        name:"Dr. Mahi Rawat",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment"
    },
]

module.exports = cardiologyApi;