const cardiologyApi = [
    {
        id:"1",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1677328782/kher_nkkz97.png",
        name:"Dr. Tangi Rajdev Patro",
        content:"Senior Diabetology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Diabetology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"delhi",
        images2:"image/patro.png"
    },
    {
        id:"2",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283436/asit/dr1_byfydh.png",
        name:"Dr. Rohan Sharma",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/untar.png"],
        appoint:"Book an Appointment",
        location:"delhi"
    },
    {
        id:"3",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283355/asit/dr_i9c19c.png",
        name:"Dr. Mahi Rawat",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/half.png"],
        appoint:"Book an Appointment",
        location:"haryana"
    },
    {
        id:"4",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283436/asit/dr1_byfydh.png",
        name:"Dr. Rohan Sharma",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"haryana"
    },
    {
        id:"5",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283439/asit/dr2_e5lg6p.png",
        name:"Dr. Sakshi Sena",
        content:"Senior Dental Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Dental",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },
    {
        id:"6",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Dental Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Dental",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },

    {
        id:"7",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283355/asit/dr_i9c19c.png",
        name:"Dr. Mahi Rawat",
        content:"Senior Dental Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Dental",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },
    {
        id:"8",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283436/asit/dr1_byfydh.png",
        name:"Dr. Rohan Sharma",
        content:"Senior Gastroenterology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Gastroenterology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },
    {
        id:"9",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283439/asit/dr2_e5lg6p.png",
        name:"Dr. Sakshi Sena",
        content:"Senior Gastroenterology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Gastroenterology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"haryana"
    },
    {
        id:"10",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Gastroenterology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Gastroenterology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },
    {
        id:"11",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Ophthalmology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Ophthalmology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"haryana",
    },
    {
        id:"12",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Ophthalmology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Ophthalmology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },
    {
        id:"13",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Ophthalmology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Ophthalmology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },
    {
        id:"14",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Internal Medicine Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Internal Medicine",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },
    {
        id:"15",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Internal Medicine Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Internal Medicine",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"haryana"
    },
    {
        id:"16",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283442/asit/dr3_rj35lo.png",
        name:"Dr. Mahi Sharma",
        content:"Senior Internal Medicine Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Internal Medicine",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"mumbai"
    },

    {
        id:"17",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283436/asit/dr1_byfydh.png",
        name:"Dr. Rohan Sharma",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/untar.png"],
        appoint:"Book an Appointment",
        location:"delhi"
    },
    {
        id:"18",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283355/asit/dr_i9c19c.png",
        name:"Dr. Mahi Rawat",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/half.png"],
        appoint:"Book an Appointment",
        location:"haryana"
    },
    {
        id:"19",
        images:"https://res.cloudinary.com/ecommerce-website/image/upload/v1675283436/asit/dr1_byfydh.png",
        name:"Dr. Rohan Sharma",
        content:"Senior Cardiology Expert at Major",
        content1:"Hospital Haryana",
        view:"View Profile",
        information:"Associate Director Cardiology",
        informationCont:"MBBS, MD, DM, FSCAI, FIC(USA), FPD (MICHIGAN USA), FPI",
        informationCont1:"(VIETNAM), FESC.",
        image1:["image/vect.png","image/vect.png","image/vect.png","image/vect.png","image/vect.png"],
        appoint:"Book an Appointment",
        location:"haryana"
    },
    
]

module.exports = cardiologyApi;