const HealthCheckupApi = [
    {
       id:"1",
       percentage:"20%",
       percentage1:"OFF",
       images:"../image/shut3.png",
       advance:"Healthkind Mini",
       range:"7 Tests Included",
       know:"Know More",
       book:"Book",
       gender:"male",
       location:"delhi",
       dis:"910",
       dis1:"499",
       detail:"Healthkind Mini (7 Test) Details",
       heart:"Heart (1 Tests)",
       heart1:"Kidney (1 Tests)",
       heart3:"Liver (3 Tests)",
       heart4:": Total Cholesterol",
       heart5:": Creatinine",
       heart6:": SGOT",
       heart7:": SGPT",
       heart8:": AST/ALT Ratio",
       heart9:"Diabetes (1 Tests)",
       heart10:"Thyroid (1 Tests)",
       heart11:" : FBS",
       heart12:": TSH",
       class:"mt-6",
    },
    {
        id:"2",
        percentage:"35%",
        percentage1:"OFF",
        off1:"off1",
        images:"../image/shut1.png",
        advance:"Healthkind Screen",
        range:"19 Tests Included",
        know:"Know More",
        book:"Book",
        gender:"baby",
        location:"delhi",
        dis:"1220",
       dis1:"799",
       detail:"Healthkind Screen (19 Test) Details",
       hear:"Heart (2 Tests)",
       hear1:"Thyroid (1 Tests)",
       hear2:"Infection (3 Tests)",
       hear3:": Total Cholesterol",
       hear4:": Triglycerides",
       hear5:": TSH",
       hear6:": Hb",
       hear7:":  TLC",
       hear8:": Platelets",
       hear9:"Diabetes (1 Tests)",
       hear10:"  Kidney (3 Tests)",
       hear11:" Liver (2 Tests)",
       hear12:": FBS",
       hear13:": BUN",
       hear14:": Creatinine",
       hear15:":  Bun/Creatinine Ratio",
       hear16:": SGOT",
       hear17:": SGPT",
       class1:"mt-20",
       class2:"mt-6",
       class3:"mt-11"
     },
     {
        id:"3",
        percentage:"64%",
        percentage1:"OFF",
        off1:"off1",
        images:"../image/shut2.png",
        advance:"Healthkind Lite",
        range:"34 Tests Included",
        know:"Know More",
        book:"Book",
        gender:"female",
        location:"mumbai",
        dis:"2950",
        dis1:"1049",
        detail:"Healthkind Lite (19 Test) Details",
        lite:"Heart (8 Tests)",
        lite1:"Bones (2 Tests)",
        lite2:"Liver (12 Tests)",
        lite3:": Total Cholesterol",
        lite4:": Triglycerides",
        lite5:": HDL Cholesterol",
        lite6:": Non HDL Cholesterol",
        lite7:": LDL Cholesterol (Calculated)",
        lite8:": VLDL Cholesterol",
        lite9:": Total Cholesterol / HDL Ratio",
        lite10:": LDL / HDL Ratio",
        lite11:": Calcium",
        lite12:": Phosphorus",
        lite13:": Bilirubin (Total",
        lite14:": Direct",
        lite15:": Indirect)",
        lite16:": SGOT",
        lite17:": SGPT",
        lite18:": AST/ALT Ratio",
        lite19:": ALP",
        lite20:": GGT",
        lite21:": Protein",
        lite22:": Albumin",
        lite23:": Globulin",
        lite24:": A:G Ratio",
        lite25:"Diabetes (1 Tests) ",
        lite26:"Kidney (8 Tests)",
        lite27:"Thyroid (3 Tests)",
        lite28:" : FBS",
        lite29:": Urea",
        lite30:": BUN",
        lite31:": Creatinine",
        lite32:": Bun/Creatinine Ratio",
        lite33:": Uric Acid",
        lite34:": Serum Sodium",
        lite35:": Serum Chloride",
        lite36:": T3",
        lite37:": T4",
        lite38:": TSH",
        liteClass:"mt-72",
        liteClass1:"mt-20",
        liteClass2:"mt-14",
        liteClass3:"mt-6",
        liteClass4:"mt-56"
     },
     {
        id:"4",
        percentage:"51%",
        percentage1:"OFF",
        images:"../image/shut3.png",
        advance:"Healthkind Complete",
        range:"81 Tests Included",
        know:"Know More",
        book:"Book",
        gender:"male",
        location:"mumbai",
        dis:"6589",
        dis1:"3199",
        detail:"Healthkind Complete (19 Test) Details",
        lite:"Heart (8 Tests)",
        lite1:"Bones (2 Tests)",
        lite2:"Liver (12 Tests)",
        lite3:": Total Cholesterol",
        lite4:": Triglycerides",
        lite5:": HDL Cholesterol",
        lite6:": Non HDL Cholesterol",
        lite7:": LDL Cholesterol (Calculated)",
        lite8:": VLDL Cholesterol",
        lite9:": Total Cholesterol / HDL Ratio",
        lite10:": LDL / HDL Ratio",
        lite11:": Calcium",
        lite12:": Phosphorus",
        lite13:": Bilirubin (Total",
        lite14:": Direct",
        lite15:": Indirect)",
        lite16:": SGOT",
        lite17:": SGPT",
        lite18:": AST/ALT Ratio",
        lite19:": ALP",
        lite20:": GGT",
        lite21:": Protein",
        lite22:": Albumin",
        lite23:": Globulin",
        lite24:": A:G Ratio",
        lite25:"Diabetes (1 Tests) ",
        lite26:"Kidney (8 Tests)",
        lite27:"Thyroid (3 Tests)",
        lite28:" : FBS",
        lite29:": Urea",
        lite30:": BUN",
        lite31:": Creatinine",
        lite32:": Bun/Creatinine Ratio",
        lite33:": Uric Acid",
        lite34:": Serum Sodium",
        lite35:": Serum Chloride",
        lite36:": T3",
        lite37:": T4",
        lite38:": TSH",
        liteClass:"mt-72",
        liteClass1:"mt-20",
        liteClass2:"mt-14",
        liteClass3:"mt-6",
        liteClass4:"mt-56",
        // comp:"Heart (1 Tests)",
        // comp1:"Kidney (7 Tests)",
        // comp2:"Liver (13 Tests)",
        // comp3:": Lipid Profile",
        // comp4:" : Urea",
        // comp5:": BUN",
        // comp6:": Creatinine",
        // comp7:": Bun/Creatinine Ratio",
        // comp8:": : Electrolytes",
        // comp9:": Uric Acid",
        // comp10:": Urine R/E",
        // comp11:":  Bilirubin (Total",
        // comp12:": Direct",
        // comp13:": Indirect)",
        // comp14:": SGOT",
        // comp15:": SGPT",
        // comp16:": AST/ALT Ratio",
        // comp17:": ALP",
        // comp18:": GGT",
        // comp19:": Protein",
        // comp10:": Albumin",
        // comp11:":  Globulin",
        // comp12:": A:G Ratio",
        // comp13:":  HBsAg",
        // comp14:" Diabetes (2 Tests)",
        // comp15:"Bones (3 Tests) ",
        // comp16:"Thyroid (3 Tests)",
        // comp16:"Nerves (1 Tests)",
        // comp17:" : Anaemia (4 Tests)",
        // comp18:": Infection (2 Tests)",
        // comp19:":  FBS",
        // comp20:": HbA1c",
        // comp21:": Vitamin D",
        // comp22:": Calcium",
        // comp23:": Phosphorus",
        // comp24:" : T3",
        // comp25:":  T4",
        // comp26:": TSH",
        // comp27:":  Vitamin B12",
        // comp28:": Iron",
        // comp29:": TIBC",
        // comp30:": UIBC",
        // comp31:": % Saturation",
        // comp32:": CBC",
        // comp33:": ESR",
        dis:"hidden"
     },
     {
        id:"5",
        percentage:"49%",
        percentage1:"OFF",
        off1:"off1",
        images:"../image/shut1.png",
        advance:"Healthkind Advance",
        range:"19 Tests Included",
        know:"Know More",
        book:"Book",
        gender:"baby",
        location:"delhi",
        dis:"7879",
        dis1:"3999",
        detail:"Healthkind Advance (19 Test) Details",
        lite:"Heart (8 Tests)",
        lite1:"Bones (2 Tests)",
        lite2:"Liver (12 Tests)",
        lite3:": Total Cholesterol",
        lite4:": Triglycerides",
        lite5:": HDL Cholesterol",
        lite6:": Non HDL Cholesterol",
        lite7:": LDL Cholesterol (Calculated)",
        lite8:": VLDL Cholesterol",
        lite9:": Total Cholesterol / HDL Ratio",
        lite10:": LDL / HDL Ratio",
        lite11:": Calcium",
        lite12:": Phosphorus",
        lite13:": Bilirubin (Total",
        lite14:": Direct",
        lite15:": Indirect)",
        lite16:": SGOT",
        lite17:": SGPT",
        lite18:": AST/ALT Ratio",
        lite19:": ALP",
        lite20:": GGT",
        lite21:": Protein",
        lite22:": Albumin",
        lite23:": Globulin",
        lite24:": A:G Ratio",
        lite25:"Diabetes (1 Tests) ",
        lite26:"Kidney (8 Tests)",
        lite27:"Thyroid (3 Tests)",
        lite28:" : FBS",
        lite29:": Urea",
        lite30:": BUN",
        lite31:": Creatinine",
        lite32:": Bun/Creatinine Ratio",
        lite33:": Uric Acid",
        lite34:": Serum Sodium",
        lite35:": Serum Chloride",
        lite36:": T3",
        lite37:": T4",
        lite38:": TSH",
        liteClass:"mt-72",
        liteClass1:"mt-20",
        liteClass2:"mt-14",
        liteClass3:"mt-6",
        liteClass4:"mt-56",
      //   adv:"Heart (1 Tests)",
      // adv1:"Kidney (6 Tests)",
      // adv2:"Nerves (1 Tests)",
      //   adv3:"Anaemia (5 Tests)",
      //   adv4:" : Lipid Profile with Direct LDL",
      // adv5:":    BUN",
      //   adv6:":  Creatinine",
      //   adv7:": BUN/Creatinine Ratio",
      // adv8:": Electrolytes",
      //   adv9:":  Uric Acid",
      // adv10:": Urine R/E",
      //   adv11:": Vitamin B12",
      //   adv12:" Diabetes (3 Tests)",
      //   adv13:" Bones (3 Tests)",
      //   adv14:" Thyroid (3 Tests)",
      //   adv15:" Liver (13 Tests)",
      //   adv16:": FBS",
      //   adv17:": HbA1c",
      //   adv18:": Microalbumin",
      //   adv19:": Vitamin D",
      //   adv10:": Calcium",
      //   adv11:": Phosphorus",
      //   adv12:": T3",
      //   adv13:": T4",
      //   adv14:": TSH",
      //   adv15:": Bilirubin (Total ",
      //   adv16:": Direct",
      //   adv16:": Indirect)",
      //   adv17:"  : SGOT",
      //   adv18:": SGPT",
      //   adv19:": ALP",
      //   adv20:": GGT",
      //   adv21:" : LDH",
      //   adv22:": Protein",
      //   adv23:" : Albumin",
      //   adv24:":  Globulin",
      //   adv25:": A:G Ratio",
      //   adv26:":  HBsAg",
      //   adv27:": CBC",
      //   adv28:": ESR",
      //   adv29:"Infection (2 Tests)",
      //   adv30:" : Iron",
      //   adv31:": UIBC",
      //   adv32:": % Saturation",
      //   adv33:": Ferritin"
     },
     {
        id:"6",
        percentage:"47%",
        percentage1:"OFF",
        off1:"off1",
        images:"../image/shut2.png",
        advance:"Healthkind Platinum",
        range:"34 Tests Included",
        willness:"complete wellness.",
        know:"Know More",
        book:"Book",
        gender:"female",
        location:"mumbai",
        dis:"9480",
        dis1:"5000",
        detail:"Healthkind Platinum (19 Test) Details",
        lite:"Heart (8 Tests)",
        lite1:"Bones (2 Tests)",
        lite2:"Liver (12 Tests)",
        lite3:": Total Cholesterol",
        lite4:": Triglycerides",
        lite5:": HDL Cholesterol",
        lite6:": Non HDL Cholesterol",
        lite7:": LDL Cholesterol (Calculated)",
        lite8:": VLDL Cholesterol",
        lite9:": Total Cholesterol / HDL Ratio",
        lite10:": LDL / HDL Ratio",
        lite11:": Calcium",
        lite12:": Phosphorus",
        lite13:": Bilirubin (Total",
        lite14:": Direct",
        lite15:": Indirect)",
        lite16:": SGOT",
        lite17:": SGPT",
        lite18:": AST/ALT Ratio",
        lite19:": ALP",
        lite20:": GGT",
        lite21:": Protein",
        lite22:": Albumin",
        lite23:": Globulin",
        lite24:": A:G Ratio",
        lite25:"Diabetes (1 Tests) ",
        lite26:"Kidney (8 Tests)",
        lite27:"Thyroid (3 Tests)",
        lite28:" : FBS",
        lite29:": Urea",
        lite30:": BUN",
        lite31:": Creatinine",
        lite32:": Bun/Creatinine Ratio",
        lite33:": Uric Acid",
        lite34:": Serum Sodium",
        lite35:": Serum Chloride",
        lite36:": T3",
        lite37:": T4",
        lite38:": TSH",
        liteClass:"mt-72",
        liteClass1:"mt-20",
        liteClass2:"mt-14",
        liteClass3:"mt-6",
        liteClass4:"mt-56",
      //   plat:"Heart (1 Tests)",
      // plat1:"Kidney (6 Tests)",
      // plat2:"Nerves (1 Tests)",
      //   plat3:"Anaemia (6 Tests)",
      //   plat4:" : Lipid Profile with Direct LDL",
      // plat5:":    BUN",
      //   plat6:":  Creatinine",
      //   plat7:": BUN/Creatinine Ratio",
      // plat8:": Electrolytes",
      //   plat9:":  Uric Acid",
      // plat10:": Urine R/E",
      //   plat11:": Vitamin B12",
      //   plat12:" Diabetes (3 Tests)",
      //   plat13:" Bones (3 Tests)",
      //   plat14:" Thyroid (3 Tests)",
      //   plat15:" Liver (13 Tests)",
      //   plat16:": FBS",
      //   plat17:": HbA1c",
      //   plat18:": Microalbumin",
      //   plat19:": Vitamin D",
      //   plat10:": Calcium",
      //   plat11:": Phosphorus",
      //   plat12:": T3",
      //   plat13:": T4",
      //   plat14:": TSH",
      //   plat15:": Bilirubin (Total ",
      //   plat16:": Direct",
      //   plat16:": Indirect)",
      //   plat17:"  : SGOT",
      //   plat18:": SGPT",
      //   plat19:": ALP",
      //   plat20:": GGT",
      //   plat21:" : LDH",
      //   plat22:": Protein",
      //   plat23:" : Albumin",
      //   plat24:":  Globulin",
      //   plat25:": A:G Ratio",
      //   plat26:":  HBsAg",
      //   plat27:": CBC",
      //   plat28:": ESR",
      //   plat29:"Infection (2 Tests)",
     },

     {
      id:"7",
      percentage:"64%",
      percentage1:"OFF",
      off1:"off1",
      images:"../image/shut2.png",
      advance:"Healthkind Active",
      range:"56 Tests Included",
      willness:"complete wellness.",
      know:"Know More",
      book:"Book",
      gender:"female",
      location:"mumbai",
      dis:"3740",
      dis1:"1349",
      detail:"Healthkind Active (19 Test) Details",
      lite:"Heart (8 Tests)",
      lite1:"Bones (2 Tests)",
      lite2:"Liver (12 Tests)",
      lite3:": Total Cholesterol",
      lite4:": Triglycerides",
      lite5:": HDL Cholesterol",
      lite6:": Non HDL Cholesterol",
      lite7:": LDL Cholesterol (Calculated)",
      lite8:": VLDL Cholesterol",
      lite9:": Total Cholesterol / HDL Ratio",
      lite10:": LDL / HDL Ratio",
      lite11:": Calcium",
      lite12:": Phosphorus",
      lite13:": Bilirubin (Total",
      lite14:": Direct",
      lite15:": Indirect)",
      lite16:": SGOT",
      lite17:": SGPT",
      lite18:": AST/ALT Ratio",
      lite19:": ALP",
      lite20:": GGT",
      lite21:": Protein",
      lite22:": Albumin",
      lite23:": Globulin",
      lite24:": A:G Ratio",
      lite25:"Diabetes (1 Tests) ",
      lite26:"Kidney (8 Tests)",
      lite27:"Thyroid (3 Tests)",
      lite28:" : FBS",
      lite29:": Urea",
      lite30:": BUN",
      lite31:": Creatinine",
      lite32:": Bun/Creatinine Ratio",
      lite33:": Uric Acid",
      lite34:": Serum Sodium",
      lite35:": Serum Chloride",
      lite36:": T3",
      lite37:": T4",
      lite38:": TSH",
      liteClass:"mt-72",
      liteClass1:"mt-20",
      liteClass2:"mt-14",
      liteClass3:"mt-6",
      liteClass4:"mt-56",
      // active:"Heart (1 Tests)",
      // active1:"Kidney (6 Tests)",
      // active2:"Infection (1 Tests)",
      //   active3:": Lipid Profile",
      //   active4:" : Urea",
      // active5:":    BUN",
      //   active6:":  Creatinine",
      //   active7:": BUN/Creatinine Ratio",
      // active8:": Electrolytes",
      // active9:"CBC",
      //   active10:"Diabetes (2 Tests)",
      // active11:"Bones (2 Tests)",
      //   active12:"Thyroid (3 Tests)",
      //   active13:"Liver (12 Tests)",
      //   active14:" : FBS",
      //   active15:" : HbA1c",
      //   active16:" : Calcium",
      //   active17:": : Phosphorus",
      //   active18:" : T3",
      //   active19:": T4",
      //   active20:": TSH",
      //   active21:": Bilirubin (Total",
      //   active22:": Direct",
      //   active23:" : Indirect)",
      //   active24:": SGOT",
      //   active25:": SGPT",
      //   active26:": AST/ALT Ratio ",
      //   active27:": ALP",
      //   active28:": GGT",
      //   active29:"  : Protein",
      //   active30:": Albumin",
      //   active31:": Globulin",
      //   active32:": A:G Ratio", 
   },

   {
      id:"8",
      percentage:"66%",
      percentage1:"OFF",
      off1:"off1",
      images:"../image/shut2.png",
      advance:"Healthkind Total",
      range:"74 Tests Included",
      know:"Know More",
      book:"Book",
      gender:"female",
      location:"mumbai",
      dis:"5400",
      dis1:"1849",
      detail:"Healthkind Total (19 Test) Details",
      lite:"Heart (8 Tests)",
      lite1:"Bones (2 Tests)",
      lite2:"Liver (12 Tests)",
      lite3:": Total Cholesterol",
      lite4:": Triglycerides",
      lite5:": HDL Cholesterol",
      lite6:": Non HDL Cholesterol",
      lite7:": LDL Cholesterol (Calculated)",
      lite8:": VLDL Cholesterol",
      lite9:": Total Cholesterol / HDL Ratio",
      lite10:": LDL / HDL Ratio",
      lite11:": Calcium",
      lite12:": Phosphorus",
      lite13:": Bilirubin (Total",
      lite14:": Direct",
      lite15:": Indirect)",
      lite16:": SGOT",
      lite17:": SGPT",
      lite18:": AST/ALT Ratio",
      lite19:": ALP",
      lite20:": GGT",
      lite21:": Protein",
      lite22:": Albumin",
      lite23:": Globulin",
      lite24:": A:G Ratio",
      lite25:"Diabetes (1 Tests) ",
      lite26:"Kidney (8 Tests)",
      lite27:"Thyroid (3 Tests)",
      lite28:" : FBS",
      lite29:": Urea",
      lite30:": BUN",
      lite31:": Creatinine",
      lite32:": Bun/Creatinine Ratio",
      lite33:": Uric Acid",
      lite34:": Serum Sodium",
      lite35:": Serum Chloride",
      lite36:": T3",
      lite37:": T4",
      lite38:": TSH",
      liteClass:"mt-72",
      liteClass1:"mt-20",
      liteClass2:"mt-14",
      liteClass3:"mt-6",
      liteClass4:"mt-56",
      // total:"Heart (1 Tests)",
      // total1:"Kidney (7 Tests)",
      // total2:"Infection (1 Tests)",
      //   total3:": Lipid Profile",
      //   total4:" : Urea",
      // total5:":    BUN",
      //   total6:":  Creatinine",
      //   total7:": BUN/Creatinine Ratio",
      // total8:": Electrolytes",
      // total9:": Uric Acid",
      //   total10:": Urine R/E",
      // total11:": CBC",
      //   total12:"Diabetes (2 Tests)",
      //   total13:"Bones (3 Tests)",
      //   total14:" Thyroid (3 Tests)",
      //   total15:" Liver (12 Tests)",
      //   total16:" :  FBS",
      //   total17:": HbA1c",
      //   total18:" : Vitamin D",
      //   total19:": Calcium",
      //   total20:": T3",
      //   total21:": : T4",
      //   total22:": Direct",
      //   total23:" : Indirect)",
      //   total24:": SGOT",
      //   total25:": SGPT",
      //   total26:": AST/ALT Ratio ",
      //   total27:": ALP",
      //   total28:": GGT",
      //   total29:"  : Protein",
      //   total30:": Albumin",
      //   total31:": Globulin",
      //   total32:": A:G Ratio", 
   },
     
]

export default HealthCheckupApi;